### PR TITLE
Fix Easy Piano support and better MIDI polyphony

### LINKED ISSUE #80: Piano support broken
I went to check out support for the external piano controller and it seems to not work with the current version of Nitroustracker. I tested the original game and it is working with the piano just to make sure. Not sure if this is high on your priorities but I could take a look if not and put in a PR.

### LINKED ISSUE #134: DS Easy Piano support non-functional
I recently tested the easy piano peripheral and couldn't get it to work with NitrousTracker. Works fine with the original game and other homebrew apps so I think it might be tracker support.

### PR DESCRIPTION
**Pull request by exelotl**
Dependent on these PRs:
https://github.com/blocksds/libnds/pull/196
https://github.com/NitrousTracker/libntxm/pull/11

I picked up an Easy Piano accessory for cheap and managed to get it working with NT!

I'm treating the piano inputs a bit differently to the onscreen piano (the note gets written to the pattern when you _hit_ the key, rather than release it) as this felt more natural.

In order to make polyphony work I had to eliminate the concept of the auto-channel (255) and replace it with tagged channels, so that whenever you release a key, the correct channel gets stopped. By coincidence, this made it possible to remove a FIXME in the MIDI implementation, though I am not able to test this, I'm pretty confident it would work.

Fixes #80, fixes #134

### CODE REVIEW

**Comment by exelotl** [comment]
CI failure is expected due to libntxm submodule being out-of-sync, but this should now be ready to review along with https://github.com/NitrousTracker/libntxm/pull/11

**Comment by prayerie** [comment]
this is such a cool feature and i can confirm as someone else with an easy piano that it works flawlessly

File: arm9/source/main.cpp [hunk 1]
```diff
@@ -3845,12 +3878,23 @@ void VblankHandler(void)
 		if(keysup & mykey_B)
 			fastscroll = false;
 	}
-
+	
+	if (keysdown & mykey_A) handlePianoPakStroke(0);
```
Comment (asiekierka) [inline arm9/source/main.cpp]: Is this debug code?

Comment (exelotl) [reply arm9/source/main.cpp]: Ahh sorry! Yes this crept in when I was bringing things up to date with the main branch. I've removed it now.

**Comment by asiekierka** [comment]
Thank you!
